### ISSUE TITLE
对象转Json字符串时候报错

### ISSUE THREAD

**Issue by yanwenxiong** [yidasanqian/json-util#5]
使用对象转Json字符串功能报错
java.lang.ClassNotFoundException: com.alibaba.fastjson.JSON
```
JsonUtil.toJsonString();
```
源码处:
```
private static AbstractJsonMapper mapper = JsonEnum.getJsonMapper();

public static AbstractJsonMapper getJsonMapper() {
        for (JsonEnum item : JsonEnum.values()) {
            if (item.getClassType().equals("jackson")) {
                return new JacksonJsonMapper();
            }
            if (item.getClassType().equals("gson")) {
                return new GsonMapper();
            }
            if (item.getClassType().equals("fastjson")) {
                return new FastJsonMapper();
            }
        }
        return null;
    }
```
这个分明是没有根据配置取对应的mapper, 而是取了枚举的第一个对应的值.

**Comment by yanwenxiong** [comment]
很明显的错误, 希望自测一下再

**Comment by yidasanqian** [comment]
自测没问题，你是不是忘了引入fastjson依赖了

**Comment by yanwenxiong** [comment]
使用上配置了jackson。应该是不需要引入fastJson吧

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: linyu<mailto:notifications@github.com>
发送时间: 2020年6月29日 10:29
收件人: yidasanqian/json-util<mailto:json-util@noreply.github.com>
抄送: tjuxiong<mailto:yanwenxiong@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [yidasanqian/json-util] 对象转Json字符串时候报错 (#5)


自测没问题，你是不是忘了引入fastjson依赖了

―

**Comment by yidasanqian** [comment]
你如果要使用fastjson就要引入它的依赖
